# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='pmedia',
            field=models.FileField(default=django.utils.timezone.now, upload_to='posts/'),
            preserve_default=False,
        ),
    ]
