# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
