# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20171025_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='faculty',
            field=models.CharField(max_length=6),
        ),
    ]
