# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-27 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_account_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
